#!/bin/bash
#set -e

export GIT_SSL_NO_VERIFY=true
mkdir -pv ~/.vim/autoload
curl --insecure -fLo ~/.vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim

# vimrc
mv -v ~/.vimrc ~/.vimrc.old 2> /dev/null
ln -sfv ~/.dotfiles/vim/.vimrc ~/.vimrc 

mkdir -pv ~/.vim/undo

vim +PlugInstall +qall

echo "install-vim finished successfully"
