#!/bin/bash
set -e

# RC files
cd $(dirname $BASH_SOURCE)
BASE=$(pwd)

ln -sfv $BASE/git/.gitconfig ~/.gitconfig

#./install-vim
ln -sfv $BASE/rubymine/.ideavimrc ~/.ideavimrc

ln -sfv $BASE/tmux/.tmux.conf ~/.tmux.conf

echo "install finished successfully"
